import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCzdcHe3H
sryRxxu45R0XegAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIIiFxMNa3fMPdBCY
TfK2fHcpDtL6DvWLawVPkU7tveDXAAAAkB7eN5/mUSK6RDHdjw43rc2RXi8moDXzv4jPMQ
PBXHT6BZNpG2Of9z6orwvRKuVARkLvwpQWTx3mBrCbrWKvw2WfpAyeR6GIXeH8ce/9uHew
C14259Wn16wCw+T2qM1nHe/jG5VDNh34kGFrjYtBD8rg15U3NRHg+z471e2lhdICR+Rxnz
N+pufjQuQHISQyaw==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
